### ISSUE TITLE
Is this approach better than using a server from llama.cpp?

### ISSUE THREAD

**Issue by MichaelWengren** [opyate/godot-llm-experiment#5]
llama.cpp has a lot of examples, the most useful one is a _server_ and its possible to communicate with it on 127.0.0.1:8080.
This approach eliminates any possible thread lockups and stutters caused by a native llama-gdextension implementation.
Or maybe I'm missing something here and this method is better?

**Comment by opyate** [comment]
Hello, sorry for the delay in replying.

Most/all games that use LLM I've seen so far uses it via an API, and the point of this experiment was to see if I can run it in-game, using the player's own GPU.

It's really an MVP, and I'm sure a lot more can be done to make it more efficient, like calling the prediction from a background thread in GDScript, etc.

Hope that helps :)
